[pytest]
asyncio_mode = auto
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --tb=short -q --cov=. --cov-report=term --cov-fail-under=60
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
env =
    DB_HOST=localhost
    DB_PORT=5434
    REDIS_URL=redis://localhost:6381/0